### ISSUE TITLE
Gemini 请求一直失败

### ISSUE THREAD

**Issue by Masque423** [godgodgame/open-all#1]
![image](https://github.com/godgodgame/open-all/assets/105150874/11fbb82e-2a4d-4169-8d98-6a44bcd25b0a)
![image](https://github.com/godgodgame/open-all/assets/105150874/948ee3a8-c522-4594-a697-766cbde58cb5)

已验证 API 没问题，网络没问题，代理放在路由器里的。

**Comment by Masque423** [comment]
左上角那个服务器启动失败不知道是什么原因啊

**Comment by godgodgame** [comment]
请更新到最新版本试一下
